package com.filesummer.gradle;

import com.filesummer.model.ProjectConfig;
import com.filesummer.model.RuleGroup;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Turns a {@link ProjectConfig} into a standalone, runnable Gradle project:
 * build.gradle (+ collect.gradle copy), settings.gradle, wrapper files and a README.
 * The generated project uses Gradle's own Copy tasks for collection; dates are
 * preserved with eachFile stamps + doLast rewrite so it runs on Gradle 7.6+.
 */
public class GradleScriptGenerator {

    private static final String TEMPLATE_DIR = "/gradle-template/wrapper/";

    public Path generate(ProjectConfig project, Path targetDir) throws IOException {
        Files.createDirectories(targetDir.resolve("gradle/wrapper"));
        String script = buildScript(project);
        Files.writeString(targetDir.resolve("build.gradle"), script, StandardCharsets.UTF_8);
        Files.writeString(targetDir.resolve("collect.gradle"), script, StandardCharsets.UTF_8);
        Files.writeString(targetDir.resolve("settings.gradle"),
                "rootProject.name = '" + groovyEscape(sanitizeName(project.getName()) + "-collector") + "'\n",
                StandardCharsets.UTF_8);
        copyTemplate("gradlew.bat", targetDir.resolve("gradlew.bat"));
        copyTemplate("gradle-wrapper.jar", targetDir.resolve("gradle/wrapper/gradle-wrapper.jar"));
        copyTemplate("gradle-wrapper.properties", targetDir.resolve("gradle/wrapper/gradle-wrapper.properties"));
        Files.writeString(targetDir.resolve("README.txt"), readme(project), StandardCharsets.UTF_8);
        return targetDir;
    }

    public String buildScript(ProjectConfig project) {
        List<RuleGroup> enabled = project.getRules().stream().filter(RuleGroup::isEnabled).toList();
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by FileSummer - project '").append(project.getName()).append("'\n");
        sb.append("// Run:  gradlew.bat collectAll    (or: gradle -b collect.gradle collectAll)\n\n");
        // imports must be at script top: inside task closures a bare `java.nio...` chain
        // would be resolved as a dynamic property on the Task delegate and fail.
        sb.append("import java.nio.file.Files\nimport java.nio.file.attribute.FileTime\n\n");
        sb.append("def outputRoot = file('").append(groovyEscape(project.getOutputDir())).append("')\n");
        sb.append("def dupStrategy = '")
          .append(project.getConflictPolicy().name().toLowerCase(Locale.ROOT))
          .append("' == 'skip' ? DuplicatesStrategy.EXCLUDE : DuplicatesStrategy.INCLUDE\n\n");
        sb.append("tasks.register('collectAll') {\n    group = 'filesummer'\n    description = 'Run all enabled task groups'\n}\n");

        if (enabled.isEmpty()) {
            sb.append("tasks.named('collectAll') { doLast { println '没有启用的任务组' } }\n");
            return sb.toString();
        }

        List<String> taskNames = new ArrayList<>();
        for (int i = 0; i < project.getRules().size(); i++) {
            RuleGroup g = project.getRules().get(i);
            if (!g.isEnabled()) {
                continue;
            }
            String taskName = "collect_" + (i + 1) + "_" + sanitizeName(g.getName());
            taskNames.add(taskName);
            appendGroupTask(sb, taskName, g, g.isRecursive());
        }
        sb.append("\ntasks.named('collectAll') {\n");
        for (String n : taskNames) {
            sb.append("    dependsOn('").append(n).append("')\n");
        }
        sb.append("}\n");
        return sb.toString();
    }

    private void appendGroupTask(StringBuilder sb, String taskName, RuleGroup g, boolean recursive) {
        String script = g.getFilterScript();
        boolean hasScript = script != null && !script.isBlank();
        if (hasScript) {
            // user keep-predicate: same vars as the in-app GroovyFilter (f/relPath/name),
            // last expression (or explicit return) decides; Groovy truth applies.
            sb.append("\ndef ").append(taskName).append("_keep(File f, String relPath, String name) {\n");
            for (String line : script.split("\r?\n")) {
                sb.append("    ").append(line).append('\n');
            }
            sb.append("}\n");
        }
        String fragVar = taskName + "_frags";
        sb.append("\ndef ").append(fragVar).append(" = [");
        for (String frag : g.getExcludeDirFragments()) {
            String f = frag == null ? "" : frag.trim();
            if (!f.isEmpty()) {
                sb.append("'").append(groovyEscape(f.toLowerCase(Locale.ROOT))).append("', ");
            }
        }
        sb.append("]\n");
        sb.append("def ").append(taskName).append("_stamps = [:]\n");
        sb.append("tasks.register('").append(taskName).append("', Copy) {\n");
        sb.append("    group = 'filesummer'\n");
        sb.append("    duplicatesStrategy = dupStrategy\n");
        for (String dir : g.getSourceDirs()) {
            sb.append("    from('").append(groovyEscape(dir)).append("') {\n");
            appendPatterns(sb, g, recursive);
            sb.append("        exclude { d -> ").append(fragVar)
              .append(".any { f -> d.relativePath.toString().toLowerCase().contains(f) } }\n");
            if (hasScript) {
                // keep directories: excluding one would prune matching files below it
                sb.append("        exclude { d -> d.file.isFile() && !").append(taskName)
                  .append("_keep(d.file, d.relativePath.pathString, d.file.name) }\n");
            }
            long[] bounds = com.filesummer.core.FileFilters.dateBoundsMillis(g);
            if (bounds != null) {
                // keep directories: excluding one would prune matching files below it
                sb.append("        exclude { d -> !d.file.isDirectory() && (");
                List<String> clauses = new ArrayList<>();
                if (bounds[0] != Long.MIN_VALUE) {
                    clauses.add("d.file.lastModified() < " + bounds[0] + "L");
                }
                if (bounds[1] != Long.MAX_VALUE) {
                    clauses.add("d.file.lastModified() >= " + bounds[1] + "L");
                }
                sb.append(String.join(" || ", clauses)).append(") }\n");
            }
            sb.append("    }\n");
        }
        String sub = g.getSubDir() == null ? "" : g.getSubDir().trim().replace('\\', '/');
        while (sub.startsWith("/")) {
            sub = sub.substring(1);
        }
        while (sub.endsWith("/")) {
            sub = sub.substring(0, sub.length() - 1);
        }
        sb.append("    ext.intoDir = ").append(sub.isEmpty() ? "outputRoot"
                : "new File(outputRoot, '" + groovyEscape(sub) + "')").append("\n");
        sb.append("    into intoDir\n");
        sb.append("    eachFile { f -> if (!f.file.isDirectory()) ")
          .append(taskName).append("_stamps[f.relativePath.pathString] = f.file.lastModified() }\n");
        sb.append("    doLast {\n");
        sb.append("        ").append(taskName).append("_stamps.each { p, t ->\n");
        sb.append("            def destFile = new File(intoDir, p)\n");
        sb.append("            if (destFile.exists()) Files.setLastModifiedTime(")
          .append("destFile.toPath(), FileTime.fromMillis(t))\n");
        sb.append("        }\n    }\n}\n");
    }

    private void appendPatterns(StringBuilder sb, RuleGroup g, boolean recursive) {
        List<String> includes = g.getIncludeSuffixes().stream()
                .map(String::trim).filter(s -> !s.isEmpty())
                .map(s -> s.startsWith(".") ? s.substring(1) : s).toList();
        String depth = recursive ? "**/" : "";
        if (includes.isEmpty()) {
            sb.append("        include '").append(depth).append("*'\n");
        } else {
            for (String sfx : includes) {
                sb.append("        include '").append(depth).append("*.")
                  .append(groovyEscape(sfx)).append("'\n");
            }
        }
        for (String sfx : g.getExcludeSuffixes()) {
            String s = sfx == null ? "" : sfx.trim();
            if (s.startsWith(".")) {
                s = s.substring(1);
            }
            if (!s.isEmpty()) {
                sb.append("        exclude '**/*.").append(groovyEscape(s)).append("'\n");
            }
        }
    }

    private String readme(ProjectConfig project) {
        return """
                FileSummer 生成工程 - 项目「%s」

                运行收集（保持原始文件修改日期）：
                    gradlew.bat collectAll
                若本机已安装 Gradle（7.6+，JDK 17+）也可以：
                    gradle -b collect.gradle collectAll

                说明：
                - 每个启用的任务组对应一个 collect_N_xxx 的 Copy 任务，可单独运行。
                - 输出根目录与每个任务组的子目录映射写在 build.gradle 顶部与各自 into 中。
                - 目录片段排除通过 exclude { closure } 按相对扫描根的路径匹配（不区分大小写），
                  排除条件优先于包含条件；请勿改用 Ant 模式匹配目录片段，否则会误伤文件名。
                - 任务组配置了 Groovy 脚本过滤时，脚本顶部会生成 <task>_keep(File f, String relPath,
                  String name) 方法（真值=保留文件），可自由修改过滤逻辑。
                """.formatted(project.getName());
    }

    private void copyTemplate(String resource, Path target) throws IOException {
        try (InputStream in = GradleScriptGenerator.class.getResourceAsStream(TEMPLATE_DIR + resource)) {
            if (in == null) {
                throw new IOException("缺少内置模板资源: " + resource
                        + "（请先执行 gradlew.bat copyWrapperTemplate）");
            }
            Files.write(target, in.readAllBytes());
        }
    }

    public static String groovyEscape(String s) {
        return s == null ? "" : s.replace("\\", "\\\\").replace("'", "\\'");
    }

    public static String sanitizeName(String s) {
        if (s == null || s.isBlank()) {
            return "group";
        }
        String ascii = s.trim().replaceAll("[^A-Za-z0-9_]", "");
        return ascii.isEmpty() ? "group" : ascii.toLowerCase(Locale.ROOT);
    }
}
